DROP TABLE IF EXISTS T_EVNT;

DROP TABLE IF EXISTS T_EVNT_USER;

DROP TABLE IF EXISTS T_NTFY;

DROP TABLE IF EXISTS T_ROLE;

DROP TABLE IF EXISTS T_USER;

DROP TABLE IF EXISTS T_USER_ROLE;

CREATE TABLE T_EVNT
(
   EVNT_ID              INT NOT NULL AUTO_INCREMENT,
   EVNT_NAME            VARCHAR(50),
   EVNT_DESC            VARCHAR(255),
   EVNT_CRT_USER_ID     INT,
   EVNT_START_DATE      DATETIME,
   EVNT_END_DATE        DATETIME,
   INS_TS               TIMESTAMP,
   PRIMARY KEY (EVNT_ID)
);

CREATE TABLE T_EVNT_USER
(
   EVNT_USER_ID         INT NOT NULL AUTO_INCREMENT,
   EVNT_ID              INT,
   USER_ID              INT,
   SIGNUP_DATE_TIME     DATETIME,
   INS_TS               TIMESTAMP,
   PRIMARY KEY (EVNT_USER_ID)
);

CREATE TABLE T_NTFY
(
   NTFY_ID              INT NOT NULL AUTO_INCREMENT,
   NTFY_CRT_USER_ID     INT,
   NTFY_SUMRY           VARCHAR(255),
   NTFY_TXT             TEXT,
   NTFY_SENT_DATE       DATETIME,
   PRIMARY KEY (NTFY_ID)
);

CREATE TABLE T_ROLE
(
   ROLE_ID              INT NOT NULL AUTO_INCREMENT,
   ROLE_NAME            VARCHAR(20),
   ROLE_DESC            VARCHAR(255),
   PRIMARY KEY (ROLE_ID)
);

CREATE TABLE T_USER
(
   USER_ID              INT NOT NULL AUTO_INCREMENT,
   FRST_NAME            VARCHAR(50),
   LAST_NAME            VARCHAR(50),
   EMAIL_ADDR           VARCHAR(255),
   AFFLT_ORG            VARCHAR(50),
   CRT_DATE             DATE,
   INS_TS               TIMESTAMP,
   PRIMARY KEY (USER_ID)
);

CREATE TABLE T_USER_ROLE
(
   USER_ROLE_ID         INT NOT NULL AUTO_INCREMENT,
   USER_ID              INT,
   ROLE_ID              INT,
   PRIMARY KEY (USER_ROLE_ID)
);

ALTER TABLE T_EVNT ADD CONSTRAINT FK_REF_4 FOREIGN KEY (EVNT_CRT_USER_ID)
      REFERENCES T_USER (USER_ID) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE T_EVNT_USER ADD CONSTRAINT FK_REF_5 FOREIGN KEY (EVNT_ID)
      REFERENCES T_EVNT (EVNT_ID) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE T_EVNT_USER ADD CONSTRAINT FK_REF_6 FOREIGN KEY (USER_ID)
      REFERENCES T_USER (USER_ID) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE T_NTFY ADD CONSTRAINT FK_REF_3 FOREIGN KEY (NTFY_CRT_USER_ID)
      REFERENCES T_USER (USER_ID) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE T_USER_ROLE ADD CONSTRAINT FK_REF_1 FOREIGN KEY (USER_ID)
      REFERENCES T_USER (USER_ID) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE T_USER_ROLE ADD CONSTRAINT FK_REF_2 FOREIGN KEY (ROLE_ID)
      REFERENCES T_ROLE (ROLE_ID) ON DELETE RESTRICT ON UPDATE RESTRICT;
